/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as ApiAccountRouteImport } from './routes/api/account'
import { Route as ApiBackstopRouteImport } from './routes/api/backstop'
import { Route as ApiCommitteeRouteImport } from './routes/api/committee'
import { Route as ApiDepositsRouteImport } from './routes/api/deposits'
import { Route as ApiFillsRouteImport } from './routes/api/fills'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiPoolRouteImport } from './routes/api/pool'
import { Route as ApiRfqRouteImport } from './routes/api/rfq'
import { Route as ApiSolvencyRouteImport } from './routes/api/solvency'
import { Route as ApiTapeRouteImport } from './routes/api/tape'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as ApiTransparencyRouteImport } from './routes/api/transparency'
import { Route as ApiVenueRouteImport } from './routes/api/venue'
import { Route as ApiWithdrawalsRouteImport } from './routes/api/withdrawals'
import { Route as LegalPrivacyPolicyRouteImport } from './routes/legal/privacy-policy'
import { Route as LegalRiskDisclosureRouteImport } from './routes/legal/risk-disclosure'
import { Route as LegalTermsOfServiceRouteImport } from './routes/legal/terms-of-service'
import { Route as ApiAuthNonceRouteImport } from './routes/api/auth/nonce'
import { Route as ApiAuthSessionRouteImport } from './routes/api/auth/session'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiBackstopHistoryRouteImport } from './routes/api/backstop_.history'
import { Route as ApiCronBackstopRebalanceRouteImport } from './routes/api/cron/backstop-rebalance'
import { Route as ApiCronFundingRouteImport } from './routes/api/cron/funding'
import { Route as ApiCronPoolRouteImport } from './routes/api/cron/pool'
import { Route as ApiCronTickRouteImport } from './routes/api/cron/tick'
import { Route as ApiOrdersIdRouteImport } from './routes/api/orders_.$id'
import { Route as ApiPoolAssociationRouteImport } from './routes/api/pool_.association'
import { Route as ApiPoolEventsRouteImport } from './routes/api/pool_.events'
import { Route as ApiPoolLeavesRouteImport } from './routes/api/pool_.leaves'
import { Route as ApiPoolMetricsRouteImport } from './routes/api/pool_.metrics'
import { Route as ApiPoolRelayRouteImport } from './routes/api/pool_.relay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRoute = ApiAccountRouteImport.update({
  id: '/api/account',
  path: '/api/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackstopRoute = ApiBackstopRouteImport.update({
  id: '/api/backstop',
  path: '/api/backstop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommitteeRoute = ApiCommitteeRouteImport.update({
  id: '/api/committee',
  path: '/api/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDepositsRoute = ApiDepositsRouteImport.update({
  id: '/api/deposits',
  path: '/api/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFillsRoute = ApiFillsRouteImport.update({
  id: '/api/fills',
  path: '/api/fills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoolRoute = ApiPoolRouteImport.update({
  id: '/api/pool',
  path: '/api/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRfqRoute = ApiRfqRouteImport.update({
  id: '/api/rfq',
  path: '/api/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSolvencyRoute = ApiSolvencyRouteImport.update({
  id: '/api/solvency',
  path: '/api/solvency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTapeRoute = ApiTapeRouteImport.update({
  id: '/api/tape',
  path: '/api/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTransparencyRoute = ApiTransparencyRouteImport.update({
  id: '/api/transparency',
  path: '/api/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVenueRoute = ApiVenueRouteImport.update({
  id: '/api/venue',
  path: '/api/venue',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWithdrawalsRoute = ApiWithdrawalsRouteImport.update({
  id: '/api/withdrawals',
  path: '/api/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyPolicyRoute = LegalPrivacyPolicyRouteImport.update({
  id: '/legal/privacy-policy',
  path: '/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRiskDisclosureRoute = LegalRiskDisclosureRouteImport.update({
  id: '/legal/risk-disclosure',
  path: '/legal/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsOfServiceRoute = LegalTermsOfServiceRouteImport.update({
  id: '/legal/terms-of-service',
  path: '/legal/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthNonceRoute = ApiAuthNonceRouteImport.update({
  id: '/api/auth/nonce',
  path: '/api/auth/nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSessionRoute = ApiAuthSessionRouteImport.update({
  id: '/api/auth/session',
  path: '/api/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackstopHistoryRoute = ApiBackstopHistoryRouteImport.update({
  id: '/api/backstop_/history',
  path: '/api/backstop/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBackstopRebalanceRoute =
  ApiCronBackstopRebalanceRouteImport.update({
    id: '/api/cron/backstop-rebalance',
    path: '/api/cron/backstop-rebalance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronFundingRoute = ApiCronFundingRouteImport.update({
  id: '/api/cron/funding',
  path: '/api/cron/funding',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPoolRoute = ApiCronPoolRouteImport.update({
  id: '/api/cron/pool',
  path: '/api/cron/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTickRoute = ApiCronTickRouteImport.update({
  id: '/api/cron/tick',
  path: '/api/cron/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersIdRoute = ApiOrdersIdRouteImport.update({
  id: '/api/orders_/$id',
  path: '/api/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoolAssociationRoute = ApiPoolAssociationRouteImport.update({
  id: '/api/pool_/association',
  path: '/api/pool/association',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoolEventsRoute = ApiPoolEventsRouteImport.update({
  id: '/api/pool_/events',
  path: '/api/pool/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoolLeavesRoute = ApiPoolLeavesRouteImport.update({
  id: '/api/pool_/leaves',
  path: '/api/pool/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoolMetricsRoute = ApiPoolMetricsRouteImport.update({
  id: '/api/pool_/metrics',
  path: '/api/pool/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPoolRelayRoute = ApiPoolRelayRouteImport.update({
  id: '/api/pool_/relay',
  path: '/api/pool/relay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/execution': typeof ExecutionRoute
  '/how-it-works': typeof HowItWorksRoute
  '/transparency': typeof TransparencyRoute
  '/api/account': typeof ApiAccountRoute
  '/api/backstop': typeof ApiBackstopRoute
  '/api/committee': typeof ApiCommitteeRoute
  '/api/deposits': typeof ApiDepositsRoute
  '/api/fills': typeof ApiFillsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/pool': typeof ApiPoolRoute
  '/api/rfq': typeof ApiRfqRoute
  '/api/solvency': typeof ApiSolvencyRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/transparency': typeof ApiTransparencyRoute
  '/api/venue': typeof ApiVenueRoute
  '/api/withdrawals': typeof ApiWithdrawalsRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/risk-disclosure': typeof LegalRiskDisclosureRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/backstop/history': typeof ApiBackstopHistoryRoute
  '/api/cron/backstop-rebalance': typeof ApiCronBackstopRebalanceRoute
  '/api/cron/funding': typeof ApiCronFundingRoute
  '/api/cron/pool': typeof ApiCronPoolRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/pool/association': typeof ApiPoolAssociationRoute
  '/api/pool/events': typeof ApiPoolEventsRoute
  '/api/pool/leaves': typeof ApiPoolLeavesRoute
  '/api/pool/metrics': typeof ApiPoolMetricsRoute
  '/api/pool/relay': typeof ApiPoolRelayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/execution': typeof ExecutionRoute
  '/how-it-works': typeof HowItWorksRoute
  '/transparency': typeof TransparencyRoute
  '/api/account': typeof ApiAccountRoute
  '/api/backstop': typeof ApiBackstopRoute
  '/api/committee': typeof ApiCommitteeRoute
  '/api/deposits': typeof ApiDepositsRoute
  '/api/fills': typeof ApiFillsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/pool': typeof ApiPoolRoute
  '/api/rfq': typeof ApiRfqRoute
  '/api/solvency': typeof ApiSolvencyRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/transparency': typeof ApiTransparencyRoute
  '/api/venue': typeof ApiVenueRoute
  '/api/withdrawals': typeof ApiWithdrawalsRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/risk-disclosure': typeof LegalRiskDisclosureRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/backstop/history': typeof ApiBackstopHistoryRoute
  '/api/cron/backstop-rebalance': typeof ApiCronBackstopRebalanceRoute
  '/api/cron/funding': typeof ApiCronFundingRoute
  '/api/cron/pool': typeof ApiCronPoolRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/pool/association': typeof ApiPoolAssociationRoute
  '/api/pool/events': typeof ApiPoolEventsRoute
  '/api/pool/leaves': typeof ApiPoolLeavesRoute
  '/api/pool/metrics': typeof ApiPoolMetricsRoute
  '/api/pool/relay': typeof ApiPoolRelayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/execution': typeof ExecutionRoute
  '/how-it-works': typeof HowItWorksRoute
  '/transparency': typeof TransparencyRoute
  '/api/account': typeof ApiAccountRoute
  '/api/backstop': typeof ApiBackstopRoute
  '/api/committee': typeof ApiCommitteeRoute
  '/api/deposits': typeof ApiDepositsRoute
  '/api/fills': typeof ApiFillsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/pool': typeof ApiPoolRoute
  '/api/rfq': typeof ApiRfqRoute
  '/api/solvency': typeof ApiSolvencyRoute
  '/api/tape': typeof ApiTapeRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/transparency': typeof ApiTransparencyRoute
  '/api/venue': typeof ApiVenueRoute
  '/api/withdrawals': typeof ApiWithdrawalsRoute
  '/legal/privacy-policy': typeof LegalPrivacyPolicyRoute
  '/legal/risk-disclosure': typeof LegalRiskDisclosureRoute
  '/legal/terms-of-service': typeof LegalTermsOfServiceRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/session': typeof ApiAuthSessionRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/backstop_/history': typeof ApiBackstopHistoryRoute
  '/api/cron/backstop-rebalance': typeof ApiCronBackstopRebalanceRoute
  '/api/cron/funding': typeof ApiCronFundingRoute
  '/api/cron/pool': typeof ApiCronPoolRoute
  '/api/cron/tick': typeof ApiCronTickRoute
  '/api/orders_/$id': typeof ApiOrdersIdRoute
  '/api/pool_/association': typeof ApiPoolAssociationRoute
  '/api/pool_/events': typeof ApiPoolEventsRoute
  '/api/pool_/leaves': typeof ApiPoolLeavesRoute
  '/api/pool_/metrics': typeof ApiPoolMetricsRoute
  '/api/pool_/relay': typeof ApiPoolRelayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/docs'
    | '/execution'
    | '/how-it-works'
    | '/transparency'
    | '/api/account'
    | '/api/backstop'
    | '/api/committee'
    | '/api/deposits'
    | '/api/fills'
    | '/api/orders'
    | '/api/pool'
    | '/api/rfq'
    | '/api/solvency'
    | '/api/tape'
    | '/api/telegram'
    | '/api/transparency'
    | '/api/venue'
    | '/api/withdrawals'
    | '/legal/privacy-policy'
    | '/legal/risk-disclosure'
    | '/legal/terms-of-service'
    | '/api/auth/nonce'
    | '/api/auth/session'
    | '/api/auth/verify'
    | '/api/backstop/history'
    | '/api/cron/backstop-rebalance'
    | '/api/cron/funding'
    | '/api/cron/pool'
    | '/api/cron/tick'
    | '/api/orders/$id'
    | '/api/pool/association'
    | '/api/pool/events'
    | '/api/pool/leaves'
    | '/api/pool/metrics'
    | '/api/pool/relay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/docs'
    | '/execution'
    | '/how-it-works'
    | '/transparency'
    | '/api/account'
    | '/api/backstop'
    | '/api/committee'
    | '/api/deposits'
    | '/api/fills'
    | '/api/orders'
    | '/api/pool'
    | '/api/rfq'
    | '/api/solvency'
    | '/api/tape'
    | '/api/telegram'
    | '/api/transparency'
    | '/api/venue'
    | '/api/withdrawals'
    | '/legal/privacy-policy'
    | '/legal/risk-disclosure'
    | '/legal/terms-of-service'
    | '/api/auth/nonce'
    | '/api/auth/session'
    | '/api/auth/verify'
    | '/api/backstop/history'
    | '/api/cron/backstop-rebalance'
    | '/api/cron/funding'
    | '/api/cron/pool'
    | '/api/cron/tick'
    | '/api/orders/$id'
    | '/api/pool/association'
    | '/api/pool/events'
    | '/api/pool/leaves'
    | '/api/pool/metrics'
    | '/api/pool/relay'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/docs'
    | '/execution'
    | '/how-it-works'
    | '/transparency'
    | '/api/account'
    | '/api/backstop'
    | '/api/committee'
    | '/api/deposits'
    | '/api/fills'
    | '/api/orders'
    | '/api/pool'
    | '/api/rfq'
    | '/api/solvency'
    | '/api/tape'
    | '/api/telegram'
    | '/api/transparency'
    | '/api/venue'
    | '/api/withdrawals'
    | '/legal/privacy-policy'
    | '/legal/risk-disclosure'
    | '/legal/terms-of-service'
    | '/api/auth/nonce'
    | '/api/auth/session'
    | '/api/auth/verify'
    | '/api/backstop_/history'
    | '/api/cron/backstop-rebalance'
    | '/api/cron/funding'
    | '/api/cron/pool'
    | '/api/cron/tick'
    | '/api/orders_/$id'
    | '/api/pool_/association'
    | '/api/pool_/events'
    | '/api/pool_/leaves'
    | '/api/pool_/metrics'
    | '/api/pool_/relay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  ExecutionRoute: typeof ExecutionRoute
  HowItWorksRoute: typeof HowItWorksRoute
  TransparencyRoute: typeof TransparencyRoute
  ApiAccountRoute: typeof ApiAccountRoute
  ApiBackstopRoute: typeof ApiBackstopRoute
  ApiCommitteeRoute: typeof ApiCommitteeRoute
  ApiDepositsRoute: typeof ApiDepositsRoute
  ApiFillsRoute: typeof ApiFillsRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiPoolRoute: typeof ApiPoolRoute
  ApiRfqRoute: typeof ApiRfqRoute
  ApiSolvencyRoute: typeof ApiSolvencyRoute
  ApiTapeRoute: typeof ApiTapeRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  ApiTransparencyRoute: typeof ApiTransparencyRoute
  ApiVenueRoute: typeof ApiVenueRoute
  ApiWithdrawalsRoute: typeof ApiWithdrawalsRoute
  LegalPrivacyPolicyRoute: typeof LegalPrivacyPolicyRoute
  LegalRiskDisclosureRoute: typeof LegalRiskDisclosureRoute
  LegalTermsOfServiceRoute: typeof LegalTermsOfServiceRoute
  ApiAuthNonceRoute: typeof ApiAuthNonceRoute
  ApiAuthSessionRoute: typeof ApiAuthSessionRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiBackstopHistoryRoute: typeof ApiBackstopHistoryRoute
  ApiCronBackstopRebalanceRoute: typeof ApiCronBackstopRebalanceRoute
  ApiCronFundingRoute: typeof ApiCronFundingRoute
  ApiCronPoolRoute: typeof ApiCronPoolRoute
  ApiCronTickRoute: typeof ApiCronTickRoute
  ApiOrdersIdRoute: typeof ApiOrdersIdRoute
  ApiPoolAssociationRoute: typeof ApiPoolAssociationRoute
  ApiPoolEventsRoute: typeof ApiPoolEventsRoute
  ApiPoolLeavesRoute: typeof ApiPoolLeavesRoute
  ApiPoolMetricsRoute: typeof ApiPoolMetricsRoute
  ApiPoolRelayRoute: typeof ApiPoolRelayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account': {
      id: '/api/account'
      path: '/api/account'
      fullPath: '/api/account'
      preLoaderRoute: typeof ApiAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backstop': {
      id: '/api/backstop'
      path: '/api/backstop'
      fullPath: '/api/backstop'
      preLoaderRoute: typeof ApiBackstopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/committee': {
      id: '/api/committee'
      path: '/api/committee'
      fullPath: '/api/committee'
      preLoaderRoute: typeof ApiCommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/deposits': {
      id: '/api/deposits'
      path: '/api/deposits'
      fullPath: '/api/deposits'
      preLoaderRoute: typeof ApiDepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fills': {
      id: '/api/fills'
      path: '/api/fills'
      fullPath: '/api/fills'
      preLoaderRoute: typeof ApiFillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pool': {
      id: '/api/pool'
      path: '/api/pool'
      fullPath: '/api/pool'
      preLoaderRoute: typeof ApiPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rfq': {
      id: '/api/rfq'
      path: '/api/rfq'
      fullPath: '/api/rfq'
      preLoaderRoute: typeof ApiRfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/solvency': {
      id: '/api/solvency'
      path: '/api/solvency'
      fullPath: '/api/solvency'
      preLoaderRoute: typeof ApiSolvencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tape': {
      id: '/api/tape'
      path: '/api/tape'
      fullPath: '/api/tape'
      preLoaderRoute: typeof ApiTapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transparency': {
      id: '/api/transparency'
      path: '/api/transparency'
      fullPath: '/api/transparency'
      preLoaderRoute: typeof ApiTransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/venue': {
      id: '/api/venue'
      path: '/api/venue'
      fullPath: '/api/venue'
      preLoaderRoute: typeof ApiVenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/withdrawals': {
      id: '/api/withdrawals'
      path: '/api/withdrawals'
      fullPath: '/api/withdrawals'
      preLoaderRoute: typeof ApiWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy-policy': {
      id: '/legal/privacy-policy'
      path: '/legal/privacy-policy'
      fullPath: '/legal/privacy-policy'
      preLoaderRoute: typeof LegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/risk-disclosure': {
      id: '/legal/risk-disclosure'
      path: '/legal/risk-disclosure'
      fullPath: '/legal/risk-disclosure'
      preLoaderRoute: typeof LegalRiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-of-service': {
      id: '/legal/terms-of-service'
      path: '/legal/terms-of-service'
      fullPath: '/legal/terms-of-service'
      preLoaderRoute: typeof LegalTermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/nonce': {
      id: '/api/auth/nonce'
      path: '/api/auth/nonce'
      fullPath: '/api/auth/nonce'
      preLoaderRoute: typeof ApiAuthNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/session': {
      id: '/api/auth/session'
      path: '/api/auth/session'
      fullPath: '/api/auth/session'
      preLoaderRoute: typeof ApiAuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backstop_/history': {
      id: '/api/backstop_/history'
      path: '/api/backstop/history'
      fullPath: '/api/backstop/history'
      preLoaderRoute: typeof ApiBackstopHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/backstop-rebalance': {
      id: '/api/cron/backstop-rebalance'
      path: '/api/cron/backstop-rebalance'
      fullPath: '/api/cron/backstop-rebalance'
      preLoaderRoute: typeof ApiCronBackstopRebalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/funding': {
      id: '/api/cron/funding'
      path: '/api/cron/funding'
      fullPath: '/api/cron/funding'
      preLoaderRoute: typeof ApiCronFundingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/pool': {
      id: '/api/cron/pool'
      path: '/api/cron/pool'
      fullPath: '/api/cron/pool'
      preLoaderRoute: typeof ApiCronPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tick': {
      id: '/api/cron/tick'
      path: '/api/cron/tick'
      fullPath: '/api/cron/tick'
      preLoaderRoute: typeof ApiCronTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders_/$id': {
      id: '/api/orders_/$id'
      path: '/api/orders/$id'
      fullPath: '/api/orders/$id'
      preLoaderRoute: typeof ApiOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pool_/association': {
      id: '/api/pool_/association'
      path: '/api/pool/association'
      fullPath: '/api/pool/association'
      preLoaderRoute: typeof ApiPoolAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pool_/events': {
      id: '/api/pool_/events'
      path: '/api/pool/events'
      fullPath: '/api/pool/events'
      preLoaderRoute: typeof ApiPoolEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pool_/leaves': {
      id: '/api/pool_/leaves'
      path: '/api/pool/leaves'
      fullPath: '/api/pool/leaves'
      preLoaderRoute: typeof ApiPoolLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pool_/metrics': {
      id: '/api/pool_/metrics'
      path: '/api/pool/metrics'
      fullPath: '/api/pool/metrics'
      preLoaderRoute: typeof ApiPoolMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pool_/relay': {
      id: '/api/pool_/relay'
      path: '/api/pool/relay'
      fullPath: '/api/pool/relay'
      preLoaderRoute: typeof ApiPoolRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  ExecutionRoute: ExecutionRoute,
  HowItWorksRoute: HowItWorksRoute,
  TransparencyRoute: TransparencyRoute,
  ApiAccountRoute: ApiAccountRoute,
  ApiBackstopRoute: ApiBackstopRoute,
  ApiCommitteeRoute: ApiCommitteeRoute,
  ApiDepositsRoute: ApiDepositsRoute,
  ApiFillsRoute: ApiFillsRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiPoolRoute: ApiPoolRoute,
  ApiRfqRoute: ApiRfqRoute,
  ApiSolvencyRoute: ApiSolvencyRoute,
  ApiTapeRoute: ApiTapeRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  ApiTransparencyRoute: ApiTransparencyRoute,
  ApiVenueRoute: ApiVenueRoute,
  ApiWithdrawalsRoute: ApiWithdrawalsRoute,
  LegalPrivacyPolicyRoute: LegalPrivacyPolicyRoute,
  LegalRiskDisclosureRoute: LegalRiskDisclosureRoute,
  LegalTermsOfServiceRoute: LegalTermsOfServiceRoute,
  ApiAuthNonceRoute: ApiAuthNonceRoute,
  ApiAuthSessionRoute: ApiAuthSessionRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiBackstopHistoryRoute: ApiBackstopHistoryRoute,
  ApiCronBackstopRebalanceRoute: ApiCronBackstopRebalanceRoute,
  ApiCronFundingRoute: ApiCronFundingRoute,
  ApiCronPoolRoute: ApiCronPoolRoute,
  ApiCronTickRoute: ApiCronTickRoute,
  ApiOrdersIdRoute: ApiOrdersIdRoute,
  ApiPoolAssociationRoute: ApiPoolAssociationRoute,
  ApiPoolEventsRoute: ApiPoolEventsRoute,
  ApiPoolLeavesRoute: ApiPoolLeavesRoute,
  ApiPoolMetricsRoute: ApiPoolMetricsRoute,
  ApiPoolRelayRoute: ApiPoolRelayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
